// flow-typed signature: 600caf56167b5717e017465b8d115692
// flow-typed version: <<STUB>>/cypress-cucumber-preprocessor_v^2.2.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-cucumber-preprocessor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-cucumber-preprocessor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/common/globalBefore' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/common/I_see_STRING_in_the_title' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/news/Google/beforeEach' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/news/Google/different' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/news/Google/openingGoogle' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/socialNetworks/Facebook/different' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/socialNetworks/Facebook/openingFacebook' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/socialNetworks/Twitter/openingTwitter' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/plugins' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/support/commands' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/support' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/plugins' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/support/commands' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/support' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/webpack.config' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/cypress-tags' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/createTestFromScenario' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/createTestsFromFeature' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/cucumberTemplate' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/cukejson/cucumberDataCollector' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/cukejson/cucumberDataCollector.test' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/cukejson/generateCucumberJson' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/cypressExecutionInstance' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/featuresLoader' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/getConfig' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/getCucumberJsonConfig' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/getStepDefinitionPathsFrom' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/getStepDefinitionPathsFrom.test' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/getStepDefinitionsPaths' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/getStepDefinitionsPaths.test' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/index.test' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/isNonGlobalStepDefinitionsMode' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/loader' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/resolveStepDefinition' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/resolveStepDefinition.test' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/stepDefinitionPath' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/stepDefinitionPath.test' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/tagsHelper' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/tagsInheritance.test' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/testHelpers/resolveFeatureFromFile' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/lib/testHelpers/setupTestFramework' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/loader' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/resolveStepDefinition' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/steps' {
  declare module.exports: any;
}

declare module 'cypress-cucumber-preprocessor/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/common/globalBefore.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/common/globalBefore'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/common/I_see_STRING_in_the_title.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/common/I_see_STRING_in_the_title'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/news/Google/beforeEach.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/news/Google/beforeEach'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/news/Google/different.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/news/Google/different'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/news/Google/openingGoogle.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/news/Google/openingGoogle'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/socialNetworks/Facebook/different.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/socialNetworks/Facebook/different'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/socialNetworks/Facebook/openingFacebook.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/socialNetworks/Facebook/openingFacebook'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/socialNetworks/Twitter/openingTwitter.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/integration/socialNetworks/Twitter/openingTwitter'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/plugins/index' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/plugins'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/plugins/index.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/plugins'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/support/commands.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/support/commands'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/support/index' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/support'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/support/index.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-example/cypress/support'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/plugins/index' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/plugins'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/plugins/index.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/plugins'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/support/commands.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/support/commands'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/support/index' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/support'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/support/index.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/support'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/webpack.config.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-cucumber-webpack-typescript-example/cypress/webpack.config'>;
}
declare module 'cypress-cucumber-preprocessor/cypress-tags.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/cypress-tags'>;
}
declare module 'cypress-cucumber-preprocessor/lib/createTestFromScenario.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/createTestFromScenario'>;
}
declare module 'cypress-cucumber-preprocessor/lib/createTestsFromFeature.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/createTestsFromFeature'>;
}
declare module 'cypress-cucumber-preprocessor/lib/cucumberTemplate.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/cucumberTemplate'>;
}
declare module 'cypress-cucumber-preprocessor/lib/cukejson/cucumberDataCollector.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/cukejson/cucumberDataCollector'>;
}
declare module 'cypress-cucumber-preprocessor/lib/cukejson/cucumberDataCollector.test.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/cukejson/cucumberDataCollector.test'>;
}
declare module 'cypress-cucumber-preprocessor/lib/cukejson/generateCucumberJson.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/cukejson/generateCucumberJson'>;
}
declare module 'cypress-cucumber-preprocessor/lib/cypressExecutionInstance.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/cypressExecutionInstance'>;
}
declare module 'cypress-cucumber-preprocessor/lib/featuresLoader.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/featuresLoader'>;
}
declare module 'cypress-cucumber-preprocessor/lib/getConfig.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/getConfig'>;
}
declare module 'cypress-cucumber-preprocessor/lib/getCucumberJsonConfig.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/getCucumberJsonConfig'>;
}
declare module 'cypress-cucumber-preprocessor/lib/getStepDefinitionPathsFrom.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/getStepDefinitionPathsFrom'>;
}
declare module 'cypress-cucumber-preprocessor/lib/getStepDefinitionPathsFrom.test.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/getStepDefinitionPathsFrom.test'>;
}
declare module 'cypress-cucumber-preprocessor/lib/getStepDefinitionsPaths.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/getStepDefinitionsPaths'>;
}
declare module 'cypress-cucumber-preprocessor/lib/getStepDefinitionsPaths.test.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/getStepDefinitionsPaths.test'>;
}
declare module 'cypress-cucumber-preprocessor/lib/index' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib'>;
}
declare module 'cypress-cucumber-preprocessor/lib/index.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib'>;
}
declare module 'cypress-cucumber-preprocessor/lib/index.test.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/index.test'>;
}
declare module 'cypress-cucumber-preprocessor/lib/isNonGlobalStepDefinitionsMode.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/isNonGlobalStepDefinitionsMode'>;
}
declare module 'cypress-cucumber-preprocessor/lib/loader.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/loader'>;
}
declare module 'cypress-cucumber-preprocessor/lib/resolveStepDefinition.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/resolveStepDefinition'>;
}
declare module 'cypress-cucumber-preprocessor/lib/resolveStepDefinition.test.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/resolveStepDefinition.test'>;
}
declare module 'cypress-cucumber-preprocessor/lib/stepDefinitionPath.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/stepDefinitionPath'>;
}
declare module 'cypress-cucumber-preprocessor/lib/stepDefinitionPath.test.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/stepDefinitionPath.test'>;
}
declare module 'cypress-cucumber-preprocessor/lib/tagsHelper.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/tagsHelper'>;
}
declare module 'cypress-cucumber-preprocessor/lib/tagsInheritance.test.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/tagsInheritance.test'>;
}
declare module 'cypress-cucumber-preprocessor/lib/testHelpers/resolveFeatureFromFile.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/testHelpers/resolveFeatureFromFile'>;
}
declare module 'cypress-cucumber-preprocessor/lib/testHelpers/setupTestFramework.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/lib/testHelpers/setupTestFramework'>;
}
declare module 'cypress-cucumber-preprocessor/loader.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/loader'>;
}
declare module 'cypress-cucumber-preprocessor/resolveStepDefinition.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/resolveStepDefinition'>;
}
declare module 'cypress-cucumber-preprocessor/steps.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/steps'>;
}
declare module 'cypress-cucumber-preprocessor/wallaby.js' {
  declare module.exports: $Exports<'cypress-cucumber-preprocessor/wallaby'>;
}
