// flow-typed signature: 050cbb3bcfc1edf9f116053a566355fd
// flow-typed version: <<STUB>>/use-debounce_v^3.4.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'use-debounce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'use-debounce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'use-debounce/esm' {
  declare module.exports: any;
}

declare module 'use-debounce/esm/useDebounce' {
  declare module.exports: any;
}

declare module 'use-debounce/esm/useDebouncedCallback' {
  declare module.exports: any;
}

declare module 'use-debounce/lib/cache' {
  declare module.exports: any;
}

declare module 'use-debounce/lib/callback' {
  declare module.exports: any;
}

declare module 'use-debounce/lib' {
  declare module.exports: any;
}

declare module 'use-debounce/lib/useDebounce' {
  declare module.exports: any;
}

declare module 'use-debounce/lib/useDebouncedCallback' {
  declare module.exports: any;
}

// Filename aliases
declare module 'use-debounce/esm/index' {
  declare module.exports: $Exports<'use-debounce/esm'>;
}
declare module 'use-debounce/esm/index.js' {
  declare module.exports: $Exports<'use-debounce/esm'>;
}
declare module 'use-debounce/esm/useDebounce.js' {
  declare module.exports: $Exports<'use-debounce/esm/useDebounce'>;
}
declare module 'use-debounce/esm/useDebouncedCallback.js' {
  declare module.exports: $Exports<'use-debounce/esm/useDebouncedCallback'>;
}
declare module 'use-debounce/lib/cache.js' {
  declare module.exports: $Exports<'use-debounce/lib/cache'>;
}
declare module 'use-debounce/lib/callback.js' {
  declare module.exports: $Exports<'use-debounce/lib/callback'>;
}
declare module 'use-debounce/lib/index' {
  declare module.exports: $Exports<'use-debounce/lib'>;
}
declare module 'use-debounce/lib/index.js' {
  declare module.exports: $Exports<'use-debounce/lib'>;
}
declare module 'use-debounce/lib/useDebounce.js' {
  declare module.exports: $Exports<'use-debounce/lib/useDebounce'>;
}
declare module 'use-debounce/lib/useDebouncedCallback.js' {
  declare module.exports: $Exports<'use-debounce/lib/useDebouncedCallback'>;
}
