// flow-typed signature: 696e9949952fe6533694db04c6e98597
// flow-typed version: <<STUB>>/validatorjs_v^3.18.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'validatorjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'validatorjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'validatorjs/coverage/Chrome 69.0.3497 (Mac OS X 10.14.0)/prettify' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/Chrome 69.0.3497 (Mac OS X 10.14.0)/sorter' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/HeadlessChrome 0.0.0 (Mac OS X 10.14.0)/prettify' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/HeadlessChrome 0.0.0 (Mac OS X 10.14.0)/sorter' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.0)/prettify' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.0)/sorter' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.5)/block-navigation' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.5)/prettify' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.5)/sorter' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/HeadlessChrome 77.0.3844 (Mac OS X 10.14.5)/block-navigation' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/HeadlessChrome 77.0.3844 (Mac OS X 10.14.5)/prettify' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/HeadlessChrome 77.0.3844 (Mac OS X 10.14.5)/sorter' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify' {
  declare module.exports: any;
}

declare module 'validatorjs/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/ar' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/az' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/be' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/bg' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/bs' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/ca' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/cs' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/cy' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/da' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/de' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/el' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/en' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/es' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/et' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/eu' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/fa' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/fi' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/fr' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/hr' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/hu' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/id' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/it' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/ja' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/ka' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/ko' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/lt' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/lv' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/mk' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/mn' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/ms' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/nb_NO' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/nl' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/pl' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/pt_BR' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/pt' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/ro' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/ru' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/se' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/sl' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/sq' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/sr' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/sv' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/tr' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/ua' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/uk' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/vi' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/zh_TW' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/lang/zh' {
  declare module.exports: any;
}

declare module 'validatorjs/dist/validator' {
  declare module.exports: any;
}

declare module 'validatorjs/sandbox/build' {
  declare module.exports: any;
}

declare module 'validatorjs/sandbox/rollup.config' {
  declare module.exports: any;
}

declare module 'validatorjs/sandbox/webpack.config' {
  declare module.exports: any;
}

declare module 'validatorjs/src/async' {
  declare module.exports: any;
}

declare module 'validatorjs/src/attributes' {
  declare module.exports: any;
}

declare module 'validatorjs/src/errors' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/ar' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/az' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/be' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/bg' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/bs' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/ca' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/cs' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/cy' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/da' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/de' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/el' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/en' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/es' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/et' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/eu' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/fa' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/fi' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/fr' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/hr' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/hu' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/id' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/it' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/ja' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/ka' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/ko' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/lt' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/lv' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/mk' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/mn' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/ms' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/nb_NO' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/nl' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/pl' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/pt_BR' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/pt' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/ro' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/ru' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/se' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/sl' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/sq' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/sr' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/sv' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/tr' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/ua' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/uk' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/vi' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/zh_TW' {
  declare module.exports: any;
}

declare module 'validatorjs/src/lang/zh' {
  declare module.exports: any;
}

declare module 'validatorjs/src/messages' {
  declare module.exports: any;
}

declare module 'validatorjs/src/rules' {
  declare module.exports: any;
}

declare module 'validatorjs/src/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'validatorjs/coverage/Chrome 69.0.3497 (Mac OS X 10.14.0)/prettify.js' {
  declare module.exports: $Exports<'validatorjs/coverage/Chrome 69.0.3497 (Mac OS X 10.14.0)/prettify'>;
}
declare module 'validatorjs/coverage/Chrome 69.0.3497 (Mac OS X 10.14.0)/sorter.js' {
  declare module.exports: $Exports<'validatorjs/coverage/Chrome 69.0.3497 (Mac OS X 10.14.0)/sorter'>;
}
declare module 'validatorjs/coverage/HeadlessChrome 0.0.0 (Mac OS X 10.14.0)/prettify.js' {
  declare module.exports: $Exports<'validatorjs/coverage/HeadlessChrome 0.0.0 (Mac OS X 10.14.0)/prettify'>;
}
declare module 'validatorjs/coverage/HeadlessChrome 0.0.0 (Mac OS X 10.14.0)/sorter.js' {
  declare module.exports: $Exports<'validatorjs/coverage/HeadlessChrome 0.0.0 (Mac OS X 10.14.0)/sorter'>;
}
declare module 'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.0)/prettify.js' {
  declare module.exports: $Exports<'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.0)/prettify'>;
}
declare module 'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.0)/sorter.js' {
  declare module.exports: $Exports<'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.0)/sorter'>;
}
declare module 'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.5)/block-navigation.js' {
  declare module.exports: $Exports<'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.5)/block-navigation'>;
}
declare module 'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.5)/prettify.js' {
  declare module.exports: $Exports<'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.5)/prettify'>;
}
declare module 'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.5)/sorter.js' {
  declare module.exports: $Exports<'validatorjs/coverage/HeadlessChrome 71.0.3563 (Mac OS X 10.14.5)/sorter'>;
}
declare module 'validatorjs/coverage/HeadlessChrome 77.0.3844 (Mac OS X 10.14.5)/block-navigation.js' {
  declare module.exports: $Exports<'validatorjs/coverage/HeadlessChrome 77.0.3844 (Mac OS X 10.14.5)/block-navigation'>;
}
declare module 'validatorjs/coverage/HeadlessChrome 77.0.3844 (Mac OS X 10.14.5)/prettify.js' {
  declare module.exports: $Exports<'validatorjs/coverage/HeadlessChrome 77.0.3844 (Mac OS X 10.14.5)/prettify'>;
}
declare module 'validatorjs/coverage/HeadlessChrome 77.0.3844 (Mac OS X 10.14.5)/sorter.js' {
  declare module.exports: $Exports<'validatorjs/coverage/HeadlessChrome 77.0.3844 (Mac OS X 10.14.5)/sorter'>;
}
declare module 'validatorjs/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify.js' {
  declare module.exports: $Exports<'validatorjs/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify'>;
}
declare module 'validatorjs/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter.js' {
  declare module.exports: $Exports<'validatorjs/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/sorter'>;
}
declare module 'validatorjs/dist/lang/ar.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/ar'>;
}
declare module 'validatorjs/dist/lang/az.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/az'>;
}
declare module 'validatorjs/dist/lang/be.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/be'>;
}
declare module 'validatorjs/dist/lang/bg.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/bg'>;
}
declare module 'validatorjs/dist/lang/bs.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/bs'>;
}
declare module 'validatorjs/dist/lang/ca.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/ca'>;
}
declare module 'validatorjs/dist/lang/cs.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/cs'>;
}
declare module 'validatorjs/dist/lang/cy.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/cy'>;
}
declare module 'validatorjs/dist/lang/da.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/da'>;
}
declare module 'validatorjs/dist/lang/de.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/de'>;
}
declare module 'validatorjs/dist/lang/el.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/el'>;
}
declare module 'validatorjs/dist/lang/en.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/en'>;
}
declare module 'validatorjs/dist/lang/es.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/es'>;
}
declare module 'validatorjs/dist/lang/et.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/et'>;
}
declare module 'validatorjs/dist/lang/eu.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/eu'>;
}
declare module 'validatorjs/dist/lang/fa.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/fa'>;
}
declare module 'validatorjs/dist/lang/fi.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/fi'>;
}
declare module 'validatorjs/dist/lang/fr.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/fr'>;
}
declare module 'validatorjs/dist/lang/hr.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/hr'>;
}
declare module 'validatorjs/dist/lang/hu.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/hu'>;
}
declare module 'validatorjs/dist/lang/id.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/id'>;
}
declare module 'validatorjs/dist/lang/it.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/it'>;
}
declare module 'validatorjs/dist/lang/ja.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/ja'>;
}
declare module 'validatorjs/dist/lang/ka.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/ka'>;
}
declare module 'validatorjs/dist/lang/ko.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/ko'>;
}
declare module 'validatorjs/dist/lang/lt.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/lt'>;
}
declare module 'validatorjs/dist/lang/lv.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/lv'>;
}
declare module 'validatorjs/dist/lang/mk.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/mk'>;
}
declare module 'validatorjs/dist/lang/mn.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/mn'>;
}
declare module 'validatorjs/dist/lang/ms.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/ms'>;
}
declare module 'validatorjs/dist/lang/nb_NO.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/nb_NO'>;
}
declare module 'validatorjs/dist/lang/nl.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/nl'>;
}
declare module 'validatorjs/dist/lang/pl.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/pl'>;
}
declare module 'validatorjs/dist/lang/pt_BR.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/pt_BR'>;
}
declare module 'validatorjs/dist/lang/pt.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/pt'>;
}
declare module 'validatorjs/dist/lang/ro.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/ro'>;
}
declare module 'validatorjs/dist/lang/ru.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/ru'>;
}
declare module 'validatorjs/dist/lang/se.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/se'>;
}
declare module 'validatorjs/dist/lang/sl.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/sl'>;
}
declare module 'validatorjs/dist/lang/sq.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/sq'>;
}
declare module 'validatorjs/dist/lang/sr.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/sr'>;
}
declare module 'validatorjs/dist/lang/sv.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/sv'>;
}
declare module 'validatorjs/dist/lang/tr.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/tr'>;
}
declare module 'validatorjs/dist/lang/ua.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/ua'>;
}
declare module 'validatorjs/dist/lang/uk.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/uk'>;
}
declare module 'validatorjs/dist/lang/vi.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/vi'>;
}
declare module 'validatorjs/dist/lang/zh_TW.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/zh_TW'>;
}
declare module 'validatorjs/dist/lang/zh.js' {
  declare module.exports: $Exports<'validatorjs/dist/lang/zh'>;
}
declare module 'validatorjs/dist/validator.js' {
  declare module.exports: $Exports<'validatorjs/dist/validator'>;
}
declare module 'validatorjs/sandbox/build.js' {
  declare module.exports: $Exports<'validatorjs/sandbox/build'>;
}
declare module 'validatorjs/sandbox/rollup.config.js' {
  declare module.exports: $Exports<'validatorjs/sandbox/rollup.config'>;
}
declare module 'validatorjs/sandbox/webpack.config.js' {
  declare module.exports: $Exports<'validatorjs/sandbox/webpack.config'>;
}
declare module 'validatorjs/src/async.js' {
  declare module.exports: $Exports<'validatorjs/src/async'>;
}
declare module 'validatorjs/src/attributes.js' {
  declare module.exports: $Exports<'validatorjs/src/attributes'>;
}
declare module 'validatorjs/src/errors.js' {
  declare module.exports: $Exports<'validatorjs/src/errors'>;
}
declare module 'validatorjs/src/lang.js' {
  declare module.exports: $Exports<'validatorjs/src/lang'>;
}
declare module 'validatorjs/src/lang/ar.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/ar'>;
}
declare module 'validatorjs/src/lang/az.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/az'>;
}
declare module 'validatorjs/src/lang/be.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/be'>;
}
declare module 'validatorjs/src/lang/bg.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/bg'>;
}
declare module 'validatorjs/src/lang/bs.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/bs'>;
}
declare module 'validatorjs/src/lang/ca.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/ca'>;
}
declare module 'validatorjs/src/lang/cs.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/cs'>;
}
declare module 'validatorjs/src/lang/cy.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/cy'>;
}
declare module 'validatorjs/src/lang/da.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/da'>;
}
declare module 'validatorjs/src/lang/de.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/de'>;
}
declare module 'validatorjs/src/lang/el.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/el'>;
}
declare module 'validatorjs/src/lang/en.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/en'>;
}
declare module 'validatorjs/src/lang/es.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/es'>;
}
declare module 'validatorjs/src/lang/et.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/et'>;
}
declare module 'validatorjs/src/lang/eu.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/eu'>;
}
declare module 'validatorjs/src/lang/fa.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/fa'>;
}
declare module 'validatorjs/src/lang/fi.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/fi'>;
}
declare module 'validatorjs/src/lang/fr.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/fr'>;
}
declare module 'validatorjs/src/lang/hr.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/hr'>;
}
declare module 'validatorjs/src/lang/hu.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/hu'>;
}
declare module 'validatorjs/src/lang/id.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/id'>;
}
declare module 'validatorjs/src/lang/it.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/it'>;
}
declare module 'validatorjs/src/lang/ja.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/ja'>;
}
declare module 'validatorjs/src/lang/ka.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/ka'>;
}
declare module 'validatorjs/src/lang/ko.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/ko'>;
}
declare module 'validatorjs/src/lang/lt.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/lt'>;
}
declare module 'validatorjs/src/lang/lv.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/lv'>;
}
declare module 'validatorjs/src/lang/mk.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/mk'>;
}
declare module 'validatorjs/src/lang/mn.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/mn'>;
}
declare module 'validatorjs/src/lang/ms.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/ms'>;
}
declare module 'validatorjs/src/lang/nb_NO.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/nb_NO'>;
}
declare module 'validatorjs/src/lang/nl.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/nl'>;
}
declare module 'validatorjs/src/lang/pl.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/pl'>;
}
declare module 'validatorjs/src/lang/pt_BR.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/pt_BR'>;
}
declare module 'validatorjs/src/lang/pt.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/pt'>;
}
declare module 'validatorjs/src/lang/ro.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/ro'>;
}
declare module 'validatorjs/src/lang/ru.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/ru'>;
}
declare module 'validatorjs/src/lang/se.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/se'>;
}
declare module 'validatorjs/src/lang/sl.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/sl'>;
}
declare module 'validatorjs/src/lang/sq.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/sq'>;
}
declare module 'validatorjs/src/lang/sr.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/sr'>;
}
declare module 'validatorjs/src/lang/sv.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/sv'>;
}
declare module 'validatorjs/src/lang/tr.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/tr'>;
}
declare module 'validatorjs/src/lang/ua.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/ua'>;
}
declare module 'validatorjs/src/lang/uk.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/uk'>;
}
declare module 'validatorjs/src/lang/vi.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/vi'>;
}
declare module 'validatorjs/src/lang/zh_TW.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/zh_TW'>;
}
declare module 'validatorjs/src/lang/zh.js' {
  declare module.exports: $Exports<'validatorjs/src/lang/zh'>;
}
declare module 'validatorjs/src/messages.js' {
  declare module.exports: $Exports<'validatorjs/src/messages'>;
}
declare module 'validatorjs/src/rules.js' {
  declare module.exports: $Exports<'validatorjs/src/rules'>;
}
declare module 'validatorjs/src/validator.js' {
  declare module.exports: $Exports<'validatorjs/src/validator'>;
}
